name: Ember CI

on:
  push:
    paths:
      - 'karutasrs-front/**'
      - '.github/workflows/ember.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install Node
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Test Ember
      uses: alexlafroscia/actions-ember-testing@master