name: Ember CI

on:
  push:
    paths:
      - 'karutasrs-front/**'
      - '.github/workflows/ember.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install Node 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -yq libgconf-2-4
        sudo apt-get install -y wget --no-install-recommends
        sudo wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
        sudo apt-get update
        sudo apt-get install -y google-chrome-unstable --no-install-recommends
        sudo rm -rf /var/lib/apt/lists/*

    - name: Create .env-test file
      run: |
        cd karutasrs-front/config
        cp .env-sample .env-test

    - name: Build Ember application
      run: |
        cd karutasrs-front
        npm i

    - name: Test Ember
      run:
        cd karutasrs-front
        ./node_modules/.bin/ember test
