name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up PostgreSQL
      uses: Harmon758/postgresql-action@v1.0.0
      with:
        # Version of PostgreSQL to use
        postgresql version: 10.11
        # POSTGRES_DB - name for the default database that is created
        postgresql db: test_db
        # POSTGRES_USER - create the specified user with superuser power
        postgresql user: test_user
        # POSTGRES_PASSWORD - superuser password
        postgresql password: test_pw

    - name: Set up Ruby 2.6
      uses: eregon/use-ruby-action@master
      with:
        ruby-version: ruby-2.6.5

    - name: Create application.yml file
      run: |
        cd karutasrs-api/config
        echo api_path: "/api" >> application.yml
        echo db_username: test_user >> application.yml
        echo db_password: test_pw >> application.yml
        echo db_port: "5432" >> application.yml
        echo db_database: test_db >> application.yml
        echo frontend_address: "localhost:4200" >> application.yml

    - name: Build Rails application
      run: |
        cd karutasrs-api
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Migrate and seed Rails
      run: |
        cd karutasrs-api
        rake db:migrate
        rake db:seed

    - name: Build and test with Rake
      run: |
        cd karutasrs-api
        bundle exec rspec
